xgSubmit   /group=Group1 /caption=Task1-Group1 /command CaptureFrames.exe Myvideo.avi 1
xgSubmit   /group=Group1 /caption=Task2-Group1 /command CaptureFrames.exe Myvideo.avi 20
xgSubmit   /group=Group1 /caption=Task3-Group1 /command CaptureFrames.exe Myvideo.avi 30
xgSubmit   /group=Group1 /caption=Task4-Group1 /command CaptureFrames.exe Myvideo.avi 40
xgSubmit  /group=Group1 /caption=Task5-Group1 /command CaptureFrames.exe Myvideo.avi 50
xgSubmit  /group=Group1 /caption=Task6-Group1 /command CaptureFrames.exe Myvideo.avi 60
xgSubmit  /group=Group1 /caption=Task7-Group1 /command CaptureFrames.exe Myvideo.avi 70
xgSubmit  /group=Group1 /caption=Task8-Group1 /command CaptureFrames.exe Myvideo.avi 80
xgSubmit  /group=Group1 /caption=Task9-Group1 /command CaptureFrames.exe Myvideo.avi 90
xgSubmit  /group=Group1 /caption=Task10-Group1 /command CaptureFrames.exe Myvideo.avi 100
xgSubmit  /group=Group1 /caption=Task11-Group1 /command CaptureFrames.exe Myvideo.avi 200
xgSubmit  /group=Group1 /caption=Task12-Group1 /command CaptureFrames.exe Myvideo.avi 300
xgSubmit   /group=Group1 /caption=Task13-Group1 /command CaptureFrames.exe Myvideo.avi 150
xgSubmit   /group=Group1 /caption=Task14-Group1 /command CaptureFrames.exe Myvideo.avi 250
xgSubmit   /group=Group1 /caption=Task15-Group1 /command CaptureFrames.exe Myvideo.avi 350
xgSubmit   /group=Group1 /caption=Task16-Group1 /command CaptureFrames.exe Myvideo.avi 400
xgSubmit  /group=Group1 /caption=Task17-Group1 /command CaptureFrames.exe Myvideo.avi 201
xgSubmit  /group=Group1 /caption=Task18-Group1 /command CaptureFrames.exe Myvideo.avi 301
xgSubmit   /group=Group1 /caption=Task19-Group1 /command CaptureFrames.exe Myvideo.avi 151
xgSubmit   /group=Group1 /caption=Task20-Group1 /command CaptureFrames.exe Myvideo.avi 251
xgSubmit   /group=Group1 /caption=Task21-Group1 /command CaptureFrames.exe Myvideo.avi 351
xgSubmit   /group=Group1 /caption=Task22-Group1 /command CaptureFrames.exe Myvideo.avi 401
xgSubmit   /group=Group1 /caption=Task23-Group1 /command CaptureFrames.exe Myvideo.avi 152
xgSubmit   /group=Group1 /caption=Task24-Group1 /command CaptureFrames.exe Myvideo.avi 252
xgSubmit   /group=Group1 /caption=Task25-Group1 /command CaptureFrames.exe Myvideo.avi 352
xgSubmit   /group=Group1 /caption=Task26-Group1 /command CaptureFrames.exe Myvideo.avi 402
xgSubmit  /group=Group1 /caption=Task27-Group1 /command CaptureFrames.exe Myvideo.avi 202
xgSubmit  /group=Group1 /caption=Task28-Group1 /command CaptureFrames.exe Myvideo.avi 302
xgSubmit   /group=Group1 /caption=Task29-Group1 /command CaptureFrames.exe Myvideo.avi 153
xgSubmit   /group=Group1 /caption=Task30-Group1 /command CaptureFrames.exe Myvideo.avi 253
xgSubmit   /group=Group1 /caption=Task31-Group1 /command CaptureFrames.exe Myvideo.avi 353
xgSubmit   /group=Group1 /caption=Task32-Group1 /command CaptureFrames.exe Myvideo.avi 403